In [2]:
import pandas as pd

In [3]:
# create tabel1.create dictionary
data={
   "name":["a","b","c"] ,
   "age":[28,30,10]
}
df=pd.DataFrame(data)
df

  name  age
0    a   28
1    b   30
2    c   10

In [4]:
# read
df=pd.read_csv("./data.csv")
df

     name  age  salary
0   hasan   32    1000
1    reza   50     900
2   sahar   20     700
3    saba   18     500
4    hadi   40     800
5     ali   20     600
6  maryam   32     800

In [5]:
df.head()

    name  age  salary
0  hasan   32    1000
1   reza   50     900
2  sahar   20     700
3   saba   18     500
4   hadi   40     800

In [6]:
df.describe()

             age       salary
count   7.000000     7.000000
mean   30.285714   757.142857
std    11.912379   171.824939
min    18.000000   500.000000
25%    20.000000   650.000000
50%    32.000000   800.000000
75%    36.000000   850.000000
max    50.000000  1000.000000

In [7]:
df["name"]

0     hasan
1      reza
2     sahar
3      saba
4      hadi
5       ali
6    maryam
Name: name, dtype: object

In [8]:
# کل سطر 2را نشان میدهد
df.iloc[2,:]

name      sahar
age          20
salary      700
Name: 2, dtype: object

In [9]:
df.iloc[4,2]

np.int64(800)

In [10]:
# filter
filtered_df=df[df["salary"]>800]
filtered_df

    name  age  salary
0  hasan   32    1000
1   reza   50     900

In [13]:
# sort
df_sort=df.sort_values("salary",ascending=False)
df_sort

     name  age  salary
0   hasan   32    1000
1    reza   50     900
4    hadi   40     800
6  maryam   32     800
2   sahar   20     700
5     ali   20     600
3    saba   18     500

In [15]:
df

     name  age  salary
0   hasan   32    1000
1    reza   50     900
2   sahar   20     700
3    saba   18     500
4    hadi   40     800
5     ali   20     600
6  maryam   32     800

In [14]:
# subset
subset=df.loc[2:4,["age","salary"]]
subset

   age  salary
2   20     700
3   18     500
4   40     800

In [16]:
# group
df_grouped=df.groupby("age")
df_grouped

In [17]:
df_grouped.count()

     name  salary
age
18      1       1
20      2       2
32      2       2
40      1       1
50      1       1

In [18]:
# add new column
df["test"]=[10,20,30,40,50,60,70]
df

     name  age  salary  test
0   hasan   32    1000    10
1    reza   50     900    20
2   sahar   20     700    30
3    saba   18     500    40
4    hadi   40     800    50
5     ali   20     600    60
6  maryam   32     800    70

In [19]:
# remove a column
df.drop("test",axis=1,inplace=True)
df

     name  age  salary
0   hasan   32    1000
1    reza   50     900
2   sahar   20     700
3    saba   18     500
4    hadi   40     800
5     ali   20     600
6  maryam   32     800

In [21]:
len(df)

7

In [23]:
# add a new row
df.loc[len(df)]={
    "name":"test",
    "age":20
}
df

     name  age  salary
0   hasan   32  1000.0
1    reza   50   900.0
2   sahar   20   700.0
3    saba   18   500.0
4    hadi   40   800.0
5     ali   20   600.0
6  maryam   32   800.0
7    test   20     NaN

In [24]:
# find all nan
df.isna()

    name    age  salary
0  False  False   False
1  False  False   False
2  False  False   False
3  False  False   False
4  False  False   False
5  False  False   False
6  False  False   False
7  False  False    True

In [25]:
# delet nan
df.dropna()

     name  age  salary
0   hasan   32  1000.0
1    reza   50   900.0
2   sahar   20   700.0
3    saba   18   500.0
4    hadi   40   800.0
5     ali   20   600.0
6  maryam   32   800.0

In [26]:
df.isna()

    name    age  salary
0  False  False   False
1  False  False   False
2  False  False   False
3  False  False   False
4  False  False   False
5  False  False   False
6  False  False   False
7  False  False    True

In [27]:
df.dropna()

     name  age  salary
0   hasan   32  1000.0
1    reza   50   900.0
2   sahar   20   700.0
3    saba   18   500.0
4    hadi   40   800.0
5     ali   20   600.0
6  maryam   32   800.0

In [28]:
df.isna()

    name    age  salary
0  False  False   False
1  False  False   False
2  False  False   False
3  False  False   False
4  False  False   False
5  False  False   False
6  False  False   False
7  False  False    True

In [29]:
df2=df.fillna(0)
df2

     name  age  salary
0   hasan   32  1000.0
1    reza   50   900.0
2   sahar   20   700.0
3    saba   18   500.0
4    hadi   40   800.0
5     ali   20   600.0
6  maryam   32   800.0
7    test   20     0.0

In [30]:
df.to_csv("new data.csv")

In [31]:
df

     name  age  salary
0   hasan   32  1000.0
1    reza   50   900.0
2   sahar   20   700.0
3    saba   18   500.0
4    hadi   40   800.0
5     ali   20   600.0
6  maryam   32   800.0
7    test   20     NaN